#!/usr/bin/env python3
# /// script
# requires-python = ">=3.8"
# dependencies = [
#     "PyYAML>=6.0",
# ]
# ///
"""Generate the readable technique registry from the YAML workflow registry."""

from pathlib import Path
from typing import Any, Dict, List, Set

try:
    import yaml
except ModuleNotFoundError as exc:  # pragma: no cover - dependency guard
    raise SystemExit(
        "PyYAML is required to generate the technique registry. "
        "Run with: uv run scripts/generate-technique-registry.py"
    ) from exc


ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = ROOT / "skills/universal-ai-execution/references/workflow-registry.yaml"
OUTPUT_PATH = ROOT / "skills/universal-ai-execution/references/technique-registry.md"

REQUIRED_WORKFLOW_FIELDS = (
    "id",
    "name",
    "category",
    "when_to_use",
    "workflow_sequence",
    "focus_areas",
    "required_outputs",
    "validation_rules",
    "common_mistakes",
)

REQUIRED_LIST_FIELDS = (
    "workflow_sequence",
    "focus_areas",
    "required_outputs",
    "validation_rules",
    "common_mistakes",
)


def load_registry() -> Dict[str, Any]:
    with REGISTRY_PATH.open("r", encoding="utf-8") as registry_file:
        registry = yaml.safe_load(registry_file)

    if not isinstance(registry, dict):
        raise ValueError("Registry must be a mapping.")

    return registry


def validate_non_empty_string(value: Any, field_name: str, workflow_id: str) -> None:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"Workflow {workflow_id!r} field {field_name!r} must be a non-empty string.")


def validate_string_list(value: Any, field_name: str, workflow_id: str) -> None:
    if not isinstance(value, list) or not value:
        raise ValueError(f"Workflow {workflow_id!r} field {field_name!r} must be a non-empty list.")

    for item in value:
        if not isinstance(item, str) or not item.strip():
            raise ValueError(
                f"Workflow {workflow_id!r} field {field_name!r} must contain only non-empty strings."
            )


def validate_registry(registry: Dict[str, Any]) -> List[Dict[str, Any]]:
    workflows = registry.get("workflows")
    if not isinstance(workflows, list):
        raise ValueError("Registry field 'workflows' must be a list.")

    workflow_count = registry.get("workflow_count")
    if workflow_count != len(workflows):
        raise ValueError(
            f"Registry workflow_count is {workflow_count!r}, but {len(workflows)} workflows were found."
        )

    default_sequence = registry.get("default_workflow_sequence")
    validate_string_list(default_sequence, "default_workflow_sequence", "default")

    seen_ids: Set[str] = set()
    duplicate_ids: Set[str] = set()

    for index, workflow in enumerate(workflows, start=1):
        if not isinstance(workflow, dict):
            raise ValueError(f"Workflow entry {index} must be a mapping.")

        missing_fields = [field for field in REQUIRED_WORKFLOW_FIELDS if field not in workflow]
        workflow_id = workflow.get("id", f"entry-{index}")
        if missing_fields:
            raise ValueError(f"Workflow {workflow_id!r} is missing fields: {', '.join(missing_fields)}.")

        validate_non_empty_string(workflow["id"], "id", str(workflow_id))
        validate_non_empty_string(workflow["name"], "name", workflow["id"])
        validate_non_empty_string(workflow["category"], "category", workflow["id"])
        validate_non_empty_string(workflow["when_to_use"], "when_to_use", workflow["id"])

        for field in REQUIRED_LIST_FIELDS:
            validate_string_list(workflow[field], field, workflow["id"])

        if workflow["id"] in seen_ids:
            duplicate_ids.add(workflow["id"])
        seen_ids.add(workflow["id"])

    if duplicate_ids:
        raise ValueError(f"Duplicate workflow ids found: {', '.join(sorted(duplicate_ids))}.")

    return workflows


def add_section(lines: List[str], title: str, items: List[str]) -> None:
    lines.extend(["", f"**{title}**", ""])
    lines.extend(f"- {item}" for item in items)


def render_registry(registry: Dict[str, Any], workflows: List[Dict[str, Any]]) -> str:
    lines = [
        "# Technique Registry",
        "",
        "Generated from `workflow-registry.yaml`. Do not edit this file manually.",
        "",
        "## Registry",
        "",
        f"- Version: {registry['version']}",
        f"- Workflow count: {registry['workflow_count']}",
        "- Source of truth: `skills/universal-ai-execution/references/workflow-registry.yaml`",
        "- Router: `skills/universal-ai-execution/SKILL.md`",
        "",
        "## Default Universal Workflow",
        "",
        "Use this sequence when no exact workflow matches:",
        "",
        " → ".join(registry["default_workflow_sequence"]),
        "",
        "## Workflows",
    ]

    for workflow in workflows:
        lines.extend(
            [
                "",
                f"### `{workflow['id']}`",
                "",
                f"- Name: {workflow['name']}",
                f"- Category: {workflow['category']}",
                f"- When to use: {workflow['when_to_use']}",
                "",
                "**Workflow Sequence**",
                "",
                " → ".join(workflow["workflow_sequence"]),
            ]
        )
        add_section(lines, "Focus Areas", workflow["focus_areas"])
        add_section(lines, "Required Outputs", workflow["required_outputs"])
        add_section(lines, "Validation Rules", workflow["validation_rules"])
        add_section(lines, "Common Mistakes", workflow["common_mistakes"])

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    registry = load_registry()
    workflows = validate_registry(registry)
    OUTPUT_PATH.write_text(render_registry(registry, workflows), encoding="utf-8")
    print(f"Generated {OUTPUT_PATH.relative_to(ROOT)} from {REGISTRY_PATH.relative_to(ROOT)}.")


if __name__ == "__main__":
    main()
